### ISSUE TITLE
TypeError while running api-gateway-stage-tag-plugin with serverless-plugin-split-stacks

### ISSUE THREAD

**Issue by mikepatrick** [mikepatrick/api-gateway-stage-tag-plugin#5]
While experimenting with serverless-plugin-split-stacks along with api-gateway-stage-tag-plugin I'm getting the below error during the tagging phase, it seems like apiStack is undefined in index.js. Is this something you came across before? Anything I can do to work around this? Thanks in advance!

```
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'PhysicalResourceId' of undefined
      at Response.<anonymous> (/Users/rcunha/workspace/mastery/node_modules/api-gateway-stage-tag-plugin/index.js:67:31)
      at Request.<anonymous> (/Users/rcunha/workspace/mastery/node_modules/serverless/node_modules/aws-sdk/lib/request.js:364:18)
```

See #4 .  Thanks @dorbsz!

**Comment by dorbsz** [comment]
Thanks @mikepatrick. Let me know when this gets released.

**Comment by mikepatrick** [comment]
Published to npm.  Sorry again for the delay, @dorbsz !

https://www.npmjs.com/package/api-gateway-stage-tag-plugin/v/1.0.6

**Comment by dorbsz** [comment]
Thank you again!! Happy president day!
